name: Run e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Start database
        run: supabase start
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          NODE_ENV: test
          CYPRESS_MAILTRAP_TOKEN: ${{secrets.MAILTRAP_TOKEN}}
          CYPRESS_MAILTRAP_ACCOUNT_ID: ${{secrets.MAILTRAP_ACCOUNT_ID}}
          CYPRESS_MAILTRAP_INBOX_ID: ${{secrets.MAILTRAP_INBOX_ID}}
          CYPRESS_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          CYPRESS_SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

