name: Run e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start
        env:
          CYPRESS_MAILTRAP_TOKEN: ${{secrets.MAILTRAP_TOKEN}}
          CYPRESS_MAILTRAP_ACCOUNT_ID: ${{secrets.MAILTRAP_ACCOUNT_ID}}
          CYPRESS_MAILTRAP_INBOX_ID: ${{secrets.MAILTRAP_INBOX_ID}}
          CYPRESS_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          CYPRESS_SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}

